version: 2
updates:
  - package-ecosystem: pub
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 5
    labels:
      - dependencies

  - package-ecosystem: pub
    directory: /hdr_player
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies

  - package-ecosystem: gradle
    directory: /android
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    open-pull-requests-limit: 3
    labels:
      - dependencies
